INFO:TeleBot:Started polling.
ERROR:TeleBot:AttributeError occurred, args=("module 'config' has no attribute 'BOTAN_TOKEN'",)
Traceback (most recent call last):
  File "C:\Users\THANHHIEU\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "main.py", line 451, in search
    track_message(msg.from_user.id, msg, 'receive_message')
  File "C:\Users\THANHHIEU\Desktop\flibusta_bot-master\src\botMsg\botMsg.py", line 40, in track_message
    return track(config.BOTAN_TOKEN, uid,
AttributeError: module 'config' has no attribute 'BOTAN_TOKEN'

